"use strict";
var FirstFudge;
(function (FirstFudge) {
    var ƒ = FudgeCore;
    document.addEventListener("DOMContentLoaded", hndLoad);
    let sun;
    let mercury;
    let venus;
    let earth;
    let mars;
    let jupiter;
    let saturn;
    let uranus;
    let neptune;
    let moon;
    let phobos;
    let deimos;
    let ganymede;
    let callisto;
    let io;
    let titan;
    let rhea;
    let iaepetus;
    let titania;
    let oberon;
    let umbriel;
    let triton;
    let proteus;
    let simspeed = 40;
    let viewport;
    function hndLoad() {
        const canvas = document.querySelector("canvas");
        const cmpCamera = new ƒ.ComponentCamera();
        FirstFudge.mesh = new ƒ.MeshSphere("Sphere");
        FirstFudge.material = new ƒ.Material("Material", ƒ.ShaderLit);
        sun = new FirstFudge.Body("Sun", 360 / 300, 10, 0);
        mercury = new FirstFudge.Body("Mercury", (360 / 88) * simspeed, 4, 10);
        venus = new FirstFudge.Body("Venus", (360 / 256) * simspeed, 3.8, 20);
        earth = new FirstFudge.Body("Earth", (360 / 356) * simspeed, 5, 35);
        moon = new FirstFudge.Body("Moon", (360 / 30) * simspeed, 2, 3);
        moon.mtxLocal.translateX(2);
        earth.addChild(moon);
        mars = new FirstFudge.Body("Mars", (360 / 687) * simspeed, 4, 45);
        phobos = new FirstFudge.Body("Phobos", -(360 / 30) * simspeed, 2, 4);
        deimos = new FirstFudge.Body("Deimos", (360 / 40) * simspeed, 2, 7);
        mars.addChild(phobos);
        mars.addChild(deimos);
        jupiter = new FirstFudge.Body("Jupiter", (360 / 4333) * simspeed, 6, 55);
        ganymede = new FirstFudge.Body("Ganimede", (360 / 200) * simspeed, 2, 3);
        callisto = new FirstFudge.Body("Callisto", -(360 / 50) * simspeed, 2, 5);
        io = new FirstFudge.Body("Io", (360 / 10) * simspeed, 2, 7);
        jupiter.addChild(ganymede);
        jupiter.addChild(callisto);
        jupiter.addChild(io);
        saturn = new FirstFudge.Body("Saturn", (360 / 10759) * simspeed, 3, 65);
        titan = new FirstFudge.Body("Titan", (360 / 40) * simspeed, 3, 4);
        rhea = new FirstFudge.Body("Rhea", (360 / 50) * simspeed, 2, 3);
        iaepetus = new FirstFudge.Body("Iapetus", (360 / 69) * simspeed, 2, 6);
        saturn.addChild(titan);
        saturn.addChild(rhea);
        saturn.addChild(iaepetus);
        uranus = new FirstFudge.Body("Uranus", (360 / 30687) * simspeed, 5, 70);
        titania = new FirstFudge.Body("Titania", (360 / 40) * simspeed, 3, 4);
        oberon = new FirstFudge.Body("Oberon", (360 / 100) * simspeed, 2, 6);
        umbriel = new FirstFudge.Body("Umbriel", (360 / 60) * simspeed, 3, 7);
        uranus.addChild(titania);
        uranus.addChild(oberon);
        uranus.addChild(umbriel);
        neptune = new FirstFudge.Body("Neptune", (360 / 60190) * simspeed, 5, 80);
        proteus = new FirstFudge.Body("Proteus", (360 / 300) * simspeed, 2, 4);
        triton = new FirstFudge.Body("Triton", (360 / 10) * simspeed, 1, 6);
        neptune.addChild(proteus);
        neptune.addChild(triton);
        let system = new ƒ.Node("System");
        system.addChild(sun);
        system.addChild(mercury);
        system.addChild(venus);
        system.addChild(earth);
        system.addChild(mars);
        system.addChild(jupiter);
        system.addChild(saturn);
        system.addChild(uranus);
        system.addChild(neptune);
        viewport = new ƒ.Viewport();
        viewport.initialize("Viewport", system, cmpCamera, canvas);
        cmpCamera.mtxPivot.translateY(200);
        //cmpCamera.mtxPivot.translateZ(-20);
        //cmpCamera.mtxPivot.rotateY(180);
        cmpCamera.mtxPivot.rotateX(90);
        ƒ.Loop.start();
        ƒ.Loop.addEventListener("loopFrame" /* ƒ.EVENT.LOOP_FRAME */, update);
    }
    function update() {
        sun.update();
        mercury.update();
        venus.update();
        earth.update();
        moon.update();
        mars.update();
        phobos.update();
        deimos.update();
        jupiter.update();
        ganymede.update();
        callisto.update();
        io.update();
        saturn.update();
        titan.update();
        rhea.update();
        iaepetus.update();
        uranus.update();
        titania.update();
        oberon.update();
        umbriel.update();
        neptune.update();
        triton.update();
        proteus.update();
        viewport.draw();
    }
})(FirstFudge || (FirstFudge = {}));
//# sourceMappingURL=SystemTest.js.map